version: 2
updates:
- package-ecosystem: "gradle"
  directories:
    - "/"
    - "/docs/examples/errorprone/"
    - "/docs/examples/jspecify/"
    - "/docs/examples/lombok/"
    - "/docs/examples/nullaway/"
  schedule:
    interval: "daily"

- package-ecosystem: "maven"
  directory: "/docs/examples/MavenExample/"
  schedule:
    interval: "daily"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
