# Workaround for https://status.dev.azure.com/_event/179641421
trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:

# Unlimited fetchDepth for misc_jobs, because of need to make contributors.tex
- job: misc_jdk8
  # dependsOn:
  #  - misc_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: wmdietl/cf-ubuntu-jdk8-plus:latest
  steps:
  - checkout: self
  - bash: ./checker/bin-devel/test-misc.sh
    displayName: test-misc.sh
- job: misc_jdk11
  # dependsOn:
  #  - misc_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: wmdietl/cf-ubuntu-jdk11-plus:latest
  steps:
  - checkout: self
  - bash: ./checker/bin-devel/test-misc.sh
    displayName: test-misc.sh
- job: misc_jdk17
  # dependsOn:
  #  - misc_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: wmdietl/cf-ubuntu-jdk17-plus:latest
  steps:
  - checkout: self
  - bash: ./checker/bin-devel/test-misc.sh
    displayName: test-misc.sh
- job: misc_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: wmdietl/cf-ubuntu-jdk21-plus:latest
  steps:
  - checkout: self
  - bash: ./checker/bin-devel/test-misc.sh
    displayName: test-misc.sh
# Disable until JDK 22 is stable
# - job: misc_jdk_latest
#   dependsOn:
#    # - canary_jobs
#    - misc_jdk21
#   pool:
#     vmImage: 'ubuntu-latest'
#   container: wmdietl/cf-ubuntu-jdk-latest-plus:latest
#   steps:
#   - checkout: self
#   - bash: ./checker/bin-devel/test-misc.sh
#     displayName: test-misc.sh
- job: misc_jdk_next
  # dependsOn:
  #  - misc_jdk21
  pool:
    vmImage: 'ubuntu-latest'
  container: wmdietl/cf-ubuntu-jdk-next-plus:latest
  steps:
  - checkout: self
  # Run test, but do not cause overall failure
  - bash: ./checker/bin-devel/test-misc.sh
    continueOnError: true
    displayName: test-misc.sh
