#!/usr/bin/env python3
"""Aids to reviewing an import of typetools commits.

The table docs/developer/typetools-divergences.tsv records where this fork names or defines
something differently from typetools.  This script uses it in three ways:

* `--range FROM..TO`: list the lines that the typetools commits in the range add and that use a
  name from the table.  A hit is a prompt to review the line, not an error: for example, typetools'
  `getAnnotation(` means this fork's `getEffectiveAnnotation(`, but `Element.getAnnotation(` is
  the same everywhere.
* `--api-diff TAG`: list the public and protected method names that classes of the typetools tag
  declare and this working tree does not, which finds divergences that nobody has written down.
* `--markdown` prints the table for docs/developer/README-eisop.md, and `--check-doc FILE` checks
  that the table in that file is up to date.
"""

import argparse
import fnmatch
import re
import subprocess
import sys
from pathlib import Path

TABLE = Path("docs/developer/typetools-divergences.tsv")
"""The divergence table, relative to the root of the repository."""

BEGIN_MARKER = "<!-- BEGIN typetools-divergences (generated by typetools-import-check.py) -->"
"""Starts the generated table in a Markdown file."""

END_MARKER = "<!-- END typetools-divergences -->"
"""Ends the generated table in a Markdown file."""

API_CLASSES = [
    "framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java",
    "framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeFactory.java",
    "framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java",
    "framework/src/main/java/org/checkerframework/framework/util/AnnotatedTypes.java",
    "framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java",
    "javacutil/src/main/java/org/checkerframework/javacutil/AnnotationUtils.java",
    "javacutil/src/main/java/org/checkerframework/javacutil/ElementUtils.java",
    "javacutil/src/main/java/org/checkerframework/javacutil/TreeUtils.java",
    "javacutil/src/main/java/org/checkerframework/javacutil/TypesUtils.java",
]
"""The classes whose API `--api-diff` compares."""

METHOD_RE = re.compile(r"^\s*(?:public|protected)\s+[^=;(]*?\b([A-Za-z_]\w*)\s*\(", re.MULTILINE)
"""Matches the declaration of a public or protected method; group 1 is its name."""


def git(*args: str) -> str:
    """Run git and return its standard output.

    Args:
        args: the arguments of the git command

    Returns:
        the standard output of the command; empty if the command fails
    """
    result = subprocess.run(["git", *args], capture_output=True, text=True, check=False)
    return result.stdout if result.returncode == 0 else ""


def read_table() -> list[dict[str, str]]:
    """Read the divergence table.

    Returns:
        one dictionary per row, with the keys kind, scope, typetools, eisop, since, and reason
    """
    rows = []
    keys = ["kind", "scope", "typetools", "eisop", "since", "reason"]
    for line in TABLE.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != len(keys):
            sys.exit(f"{TABLE}: expected {len(keys)} tab-separated fields, got: {line}")
        rows.append(dict(zip(keys, fields, strict=True)))
    return rows


def name_pattern(token: str) -> re.Pattern[str] | None:
    """Return a pattern that finds a table name used in code.

    Args:
        token: a name from the table, such as `getAnnotation(`

    Returns:
        a pattern for the call or declaration of the method, or None if the name is not a method
    """
    match = re.fullmatch(r"([A-Za-z_]\w*)\(\)?", token)
    if not match:
        return None
    return re.compile(r"\b" + re.escape(match.group(1)) + r"\(")


def scan_range(commit_range: str) -> int:
    """Print the added lines of a range of commits that use a name from the table.

    Args:
        commit_range: a range such as `checker-framework-3.54.0..checker-framework-3.54.1`

    Returns:
        the number of lines printed
    """
    patterns = []
    for row in read_table():
        if row["kind"] in ("collision", "rename"):
            pattern = name_pattern(row["typetools"])
            if pattern:
                patterns.append((pattern, row))
    commits = git("log", "--no-merges", "--reverse", "--format=%H", commit_range).split()
    count = 0
    for commit in commits:
        diff = git("show", "-U0", "--format=%h %s", commit, "--", "*.java")
        header = diff.split("\n", 1)[0]
        path = ""
        printed_header = False
        for line in diff.split("\n")[1:]:
            if line.startswith("+++ "):
                path = line[6:]
            elif line.startswith("+") and not line.startswith("+++"):
                for pattern, row in patterns:
                    if pattern.search(line):
                        if not printed_header:
                            print(f"\n{header}")
                            printed_header = True
                        print(f"  {path}: {line[1:].strip()[:110]}")
                        print(
                            f"      typetools {row['typetools']} = here {row['eisop']}"
                            f" ({row['kind']}, {row['scope']})"
                        )
                        count += 1
    print(f"\n{count} added line(s) use a name from {TABLE}; review each.")
    return count


def method_names(source: str) -> set[str]:
    """Return the names of the public and protected methods that a Java source file declares.

    Args:
        source: the text of a Java source file

    Returns:
        the names of its public and protected methods
    """
    return {m.group(1) for m in METHOD_RE.finditer(source)}


def api_diff(tag: str) -> None:
    """Print the method names that a tag declares and the working tree does not.

    Args:
        tag: a git revision of typetools, such as `checker-framework-3.54.1`
    """
    known = [row["typetools"].rstrip("()") for row in read_table()]
    for path in API_CLASSES:
        upstream = git("show", f"{tag}:{path}")
        if not upstream:
            continue
        ours = Path(path).read_text(encoding="utf-8") if Path(path).exists() else ""
        missing = sorted(
            name
            for name in method_names(upstream) - method_names(ours)
            if not any(fnmatch.fnmatchcase(name, pattern) for pattern in known)
        )
        if missing:
            print(f"{Path(path).name}: {', '.join(missing)}")


def markdown() -> str:
    """Return the divergence table as a Markdown table, between its markers.

    Returns:
        the Markdown text
    """
    lines = [
        BEGIN_MARKER,
        "",
        "| Kind | Scope | Typetools | EISOP | Since | Why |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in read_table():
        cells = [row["kind"], row["scope"], f"`{row['typetools']}`", f"`{row['eisop']}`"]
        cells += [row["since"], row["reason"].replace("|", "\\|")]
        lines.append("| " + " | ".join(cells) + " |")
    lines += ["", END_MARKER]
    return "\n".join(lines)


def check_doc(doc: str) -> int:
    """Check that the table in a Markdown file is the generated one.

    Args:
        doc: the path of a Markdown file with the generated table between its markers

    Returns:
        0 if the table is up to date, 1 otherwise
    """
    text = Path(doc).read_text(encoding="utf-8")
    start = text.find(BEGIN_MARKER)
    end = text.find(END_MARKER)
    if start < 0 or end < 0:
        print(f"{doc} does not contain the markers {BEGIN_MARKER!r} and {END_MARKER!r}")
        return 1
    if text[start : end + len(END_MARKER)] != markdown():
        print(f"{doc}: the divergence table is out of date; replace it by the output of --markdown")
        return 1
    return 0


def main() -> int:
    """Run the command that the arguments select.

    Returns:
        the exit status
    """
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--range", help="list added lines that use a name from the table")
    group.add_argument("--api-diff", metavar="TAG", help="list typetools-only method names")
    group.add_argument("--markdown", action="store_true", help="print the table as Markdown")
    group.add_argument("--check-doc", metavar="FILE", help="check the table in a Markdown file")
    args = parser.parse_args()
    if args.range:
        scan_range(args.range)
    elif args.api_diff:
        api_diff(args.api_diff)
    elif args.markdown:
        print(markdown())
    else:
        return check_doc(args.check_doc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
